# Generated by Django 6.1 on 2026-09-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
