# Generated by Django 6.1 on 2026-09-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('label_pt', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['label_pt'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('launch_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('perfumer', models.CharField(blank=True, max_length=150)),
                ('concentration', models.CharField(choices=[('cologne', 'Cologne'), ('edt', 'EDT'), ('edp', 'EDP'), ('parfum', 'Parfum'), ('extrait', 'Extrait')], default='edp', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accords', models.ManyToManyField(blank=True, related_name='perfumes', to='catalog.accord')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfumes', to='catalog.brand')),
                ('notes_base', models.ManyToManyField(blank=True, related_name='base_of', to='catalog.note')),
                ('notes_heart', models.ManyToManyField(blank=True, related_name='heart_of', to='catalog.note')),
                ('notes_top', models.ManyToManyField(blank=True, related_name='top_of', to='catalog.note')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'name'), name='unique_perfume_per_brand')],
            },
        ),
    ]
